config/routes.rb
Rails.application.routes.draw do
  resources :rentals
  resources :movie_genres
  resources :vhs
  resources :movies
  resources :genres
  resources :clients
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :rentals
    has_many :vhs, through: :rentals
    validates :name, presence: true
    validates :home_address, presence: true, uniqueness: true 

    def movie_from_vhs
        self.vhs.map{|vhs| vhs.movie.title}
    end
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :movie_genres
    has_many :movies, through: :movie_genres
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :vhs 
    has_many :rentals, through: :vhs 
    has_many :movie_genres
    has_many :genres, through: :movie_genres

end

app/models/movie_genre.rb
class MovieGenre < ApplicationRecord
  belongs_to :genre
  belongs_to :movie
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :client
  belongs_to :vhs

  def movie_from_vhs
    Movie.find(self.vhs.movie_id)
  end 
  
end

app/models/vhs.rb
class Vhs < ApplicationRecord
  belongs_to :movie
  has_many :rentals
  has_many :clients, through: :rentals

  after_initialize :add_serial_number

  def movie_from_id
    Movie.find(self.movie.id)
  end

  def available_to_rent
    doug = self.rentals.select{|rental| !rental.current}
    doug.count
  end
  
  def is_available_to_rent?
    Rental.where(vhs_id: self.id, current: true)
  end 

  private

  # generates serial number based on the title
  def add_serial_number
      # binding.pry
      serial_number = serial_number_stub
      # Converting to Base 36 can be useful when you want to generate random combinations of letters and numbers, since it counts using every number from 0 to 9 and then every letter from a to z. Read more about base 36 here: https://en.wikipedia.org/wiki/Senary#Base_36_as_senary_compression
      alphanumerics = (0...36).map{ |i| i.to_s 36 }
      13.times{|t| serial_number << alphanumerics.sample}
      self.update(serial_number: serial_number)
  end

  def long_title?
      self.movie.title && self.movie.title.length > 2
  end

  def two_part_title?
      self.movie.title.split(" ")[1] && self.movie.title.split(" ")[1].length > 2
  end

  def serial_number_stub
      # binding.pry
      return "X" if self.movie.title.nil?
      return self.movie.title.split(" ")[1][0..3].gsub(/s/, "").upcase + "-" if two_part_title?
      return self.movie.title.gsub(/s/, "").upcase + "-" unless long_title?
      self.movie.title[0..3].gsub(/s/, "").upcase + "-"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
    before_action :find_client, only: [:show]

    def index 
        @clients = Client.all
    end

    def show 
        @rentals = @client.rentals
        @vhs = @client.vhs
    end 

    def new 
        @errors = flash[:errors]
        @client = Client.new
    end

    def create 
        @client = Client.create(client_params)

        if @client.valid?
            redirect_to client_path(@client)
        else
            flash[:errors] = @client.errors.full_messages
            redirect_to new_client_path
        end
    end 

    # def 

    private 

    def find_client
        @client = Client.find(params[:id])
    end 

    def client_params
        params.require(:client).permit(:name, :home_address)
    end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
    before_action :find_genre
    
    def index 
        @genres = Genre.all
    end

    def show 
    end

    private 

    def find_genre
        @genre = Genre.find(params[:id])
    end

end

app/controllers/movie_genres_controller.rb
class MovieGenresController < ApplicationController
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    before_action :find_movie, only: [:show]
    def index 
        @movies = Movie.all
    end 

    def show 
        @vhs = @movie.vhs
    end

    private 
    def find_movie
        @movie = Movie.find(params[:id])
    end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
    before_action :find_rental, only: [:show]
    
    def index 
        @rentals = Rental.all
    end 

    def show 
    end 

    private 

    def find_rental
        @rental = Rental.find(params[:id])
    end
end

app/controllers/vhs_controller.rb
class VhsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/movie_genres_helper.rb
module MovieGenresHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/helpers/vhs_helper.rb
module VhsHelper
end

app/views/clients/index.erb
<h1>All Clients</h1>
<main>

<ol>
  <% @clients.each do |client| %>
    <li><%= link_to client.name, client %>, <em> Address: </em> <%= client.home_address %></li>
  <% end  %>
</ol>

<p><%= link_to "Add a new client", new_client_path %></p>
</main>

app/views/clients/new.erb
<h1> New Client! </h1>
<main>
  <% if @errors %>
    <ul>
    <% @errors.each do |error| %>
      <li><%= error %></li>
    <% end %>
    </ul>
  <% end %>
<hr>
    <p><%= form_for @client do |f| %></p>
    <p><%= f.label :name, "Name" %>
    <%= f.text_field :name %></p>
    <p><%= f.label :home_address, "Address" %>
    <%= f.text_field :home_address %></p>
    <hr>
    <p><%= f.submit "Submit client" %></p>
    <% end %>
</main>

app/views/clients/show.erb
<h1> Client's Profile </h1>
<main>
<hr>
  <p><b> Name: </b><%= @client.name %></p>
  <p><b> Address: </b><%= @client.home_address %></p>
  <p><b> Rentals: </b>
    <ol>
      <% @rentals.each do |rental| %>
        <li><%= link_to rental.vhs.movie_from_id.title, movie_path(rental.movie_from_vhs) %></li>
      <% end %> 
    </ol>
  </p>
</main>

app/views/genres/index.erb
<h1>All Genres</h1>
<main>

    <ol>
        <% @genres.each do |genre| %>
            <li><%= link_to genre.name, genre %></li>
        <% end  %>
    </ol>
</main>

app/views/movies/index.erb
<h1>All Movies</h1>
<main>

    <ol>
        <% @movies.each do |movie| %>
            <li><%= link_to movie.title, movie %>, <em> Year: </em><%= movie.year %></li>
        <% end  %>
    </ol>
</main>

app/views/movies/show.erb
<h1> Movie's Information </h1>
<main>
<hr>
  <ul>
  <li><b> Name: </b><%= @movie.title %>, <%= @movie.year %></li>
  <li><b> Length: </b><%= @movie.length %> minutes</li>
  <li><b> Director: </b><%= @movie.director %></li>
  <li><b> Description: </b><%= @movie.description %></li>
  <li><b> Female director: </b><%= @movie.female_director %></li>
  </ul>
  <p><b> Vhs copies: </b><%= @vhs.size %>
    <ul><% @vhs.each do |v| %>
      <li><%= v.serial_number %></li>
    <% end %>
    </ul>
  <p><b> Vhs available: </b><% @vhs.each do |v| %>
      <%= v.available_to_rent %>      
      <% end %> 
  </p>
  <p><%= link_to "All movies", movies_path %></p>
</main>

app/views/rentals/index.erb
<h1>All Rentals</h1>
<main>

    <ol>
        <% @rentals.each do |rental| %>
            <li><%= link_to rental.vhs.movie_from_id, rental %>, Rented: <%= rental.current %></li>
        <% end  %>
    </ol>
</main>